pom.xml, src/main/java/gazeplay/DefaultGamesLocator.java, src/main/java/gazeplay/GameSpec.java, src/main/java/gazeplay/GamesLocator.java, src/main/java/gazeplay/GazePlay.java, src/main/java/gazeplay/GazePlayLauncher.java
Hi Didier,
Here is little refactoring of the GazePlay class.
My goal was to separate the 3 concerns : 
- the java main class for the executable JAR
- the GazePlay main screen
- the definition of the list of games
=> Gaze play class refactorings

pom.xml, src/main/java/arduino/windmill/Choices.java, src/main/java/blocs/Blocs.java, src/main/java/bubbles/Bubble.java, src/main/java/creampie/Hand.java, src/main/java/eyetrackersservers/EyeTribeServer.java, src/main/java/eyetrackersservers/GazeListener.java, src/main/java/gaze/EyeTribeGazeListener.java, src/main/java/gaze/FuzzyGazeListener.java, src/main/java/gaze/GazeListener.java, src/main/java/gaze/GazeUtils.java, src/main/java/gaze/SecondScreen.java, src/main/java/gaze/configuration/Configuration.java, src/main/java/gazeplay/DefaultGamesLocator.java, src/main/java/gazeplay/GazePlay.java, src/main/java/gazeplay/GazePlayLauncher.java, src/main/java/pictogrammes/Pictos.java, src/main/java/sample/LightningSimulator.java, src/main/java/sample/TETSimple.java, src/main/java/sample/TestGaze.java, src/main/java/tobii/Tobii.java, src/main/java/utils/arduino/ArduinoSerialCommunication.java, src/main/java/utils/games/License.java, src/main/java/utils/games/Utils.java, src/main/java/utils/games/multilinguism/Multilinguism.java, src/main/java/utils/games/stats/Stats.java, src/main/resources/logback.xml
introduced logging API slf4j, along with logging framework logback, 
plus other adapters to redirect logs produced by libraries using System.out or other. 
Did not optimized logging level yet. All level are either INFO or ERROR for the moment. 
Also further tuning using message placeholder (instead of concatenation) may be needed. 
logback configuration include simple pattern for logging to CONSOLE, and extended pattern for logging to FILE (log file is saved in the GazePlay directory)
=> introduced logging framework for logging to both console and file

.travis.yml, gazeplay-commons/pom.xml, gazeplay-melordi/pom.xml, gazeplay-picto-pick/pom.xml, gazeplay-side-projects/pom.xml, gazeplay-tobii-setup/pom.xml, gazeplay/pom.xml
(openjdk8 requires additional package to be installed 'openjfx')
=> making Travis CI work on both oraclejdk8 and openjdk8

gazeplay-dist/descriptor.xml, gazeplay-dist/src/main/bin/gazeplay.bat, gazeplay-dist/src/main/bin/tobii-setup.bat
please see commit messages for details
=> Improvement in zip dist

gazeplay/src/main/java/net/gazeplay/utils/ConfigurationDisplay.java
when user does not select a file
=> fixed NullPointerException in ConfigurationDisplay

gazeplay-commons/src/main/java/gaze/configuration/Configuration.java, gazeplay/src/main/java/net/gazeplay/utils/ConfigurationDisplay.java
in order to use consistent file encoding (UTF-8)
fixes issue #84
=> fixed configuration file load and store 

gazeplay-commons/src/main/java/net/gazeplay/utils/stats/Stats.java, gazeplay-commons/src/main/java/utils/games/Utils.java, gazeplay/src/main/resources/logback.xml
* improvements in logging : console does not print DEBUG level anymore, but the log file include all levels
* images scanning was too verbose, using DEBUG level for this
* log the heat map size
=> Improvements in logging

gazeplay/src/main/java/net/gazeplay/commons/utils/Bravo.java, gazeplay/src/main/java/net/gazeplay/games/blocs/Blocs.java, gazeplay/src/main/java/net/gazeplay/games/magiccards/Card.java, gazeplay/src/main/java/net/gazeplay/games/whereisit/WhereIsIt.java
use built-in JavaFx Fade and Scale Transitions + also play the sound with a lower volume
=> improvement in Bravo animation

gazeplay-commons/pom.xml, gazeplay-data/pom.xml, gazeplay-dist/pom.xml, gazeplay-dlls/pom.xml, gazeplay-melordi/pom.xml, gazeplay-picto-pick/pom.xml, gazeplay-side-projects/pom.xml, gazeplay/pom.xml, pom.xml
This reverts commit 54afd0c562f30809f96c3ffc7e5b248a7d6c9f6a.
as proposed in #109
This PR fixes issue #109
=> Revert "tobii stepus dependence deleted in gazeplay dist pom"

gazeplay/src/main/java/net/gazeplay/DefaultGamesLocator.java, gazeplay/src/main/java/net/gazeplay/games/whereisit/WhereIsIt.java
because static code should be avoided
=> refactored WhereIsIt class to remove usage of static variables

gazeplay/src/main/java/net/gazeplay/commons/utils/Bravo.java, gazeplay/src/main/java/net/gazeplay/games/blocs/Blocs.java, gazeplay/src/main/java/net/gazeplay/games/magiccards/Card.java, gazeplay/src/main/java/net/gazeplay/games/whereisit/GameSizing.java, gazeplay/src/main/java/net/gazeplay/games/whereisit/GameSizingComputer.java, gazeplay/src/main/java/net/gazeplay/games/whereisit/WhereIsIt.java
Multiple refactorings and improvements on games 'where is it'
Addressing both code readability and user interface performance improvements (animations)
=> 'Where is it' game code improvement

gazeplay/src/main/java/net/gazeplay/commons/utils/Bravo.java, gazeplay/src/main/java/net/gazeplay/commons/utils/Home.java, gazeplay/src/main/java/net/gazeplay/commons/utils/HomeUtils.java, gazeplay/src/main/java/net/gazeplay/games/blocs/Blocs.java, gazeplay/src/main/java/net/gazeplay/games/magiccards/Card.java, gazeplay/src/main/java/net/gazeplay/games/whereisit/WhereIsIt.java
Reverts schwabdidier/GazePlay#122
=> Revert "Home utils refactoring and ui improvements"

gazeplay/src/main/java/net/gazeplay/commons/utils/HomeUtils.java
simpler way to remove elements, no need to move objects outside the screen
=> HomeUtils.clear()

gazeplay/src/main/java/net/gazeplay/commons/utils/Bravo.java, gazeplay/src/main/java/net/gazeplay/games/whereisit/WhereIsIt.java, gazeplay/src/test/java/net/gazeplay/commons/utils/BravoTestVisual.java, gazeplay/src/test/resources/logback.xml
initially proposed in PR #122
I hope this fixes animation issues reported in #123
* improved animation timing (fade in + zoom in and out + sound now play much better)
* better performance and responsiveness
* the next round now only starts when the bravo animation and sound is fully finished
* the next round only start after a small delay (set to 5000 ms but you can fine tune it if this is not the appropriate value)
* timing can be tuned by just changing the private static constants at the beginning of the class. I tried to have meaningful variables and constants for readability
this PR depends on PR #125 (so it includes it)
=> Bravo improvements

gazeplay-commons/src/main/java/net/gazeplay/commons/utils/games/Utils.java, gazeplay/src/main/java/net/gazeplay/DefaultGamesLocator.java, gazeplay/src/main/java/net/gazeplay/GameSpec.java, gazeplay/src/main/java/net/gazeplay/GazePlay.java, gazeplay/src/main/java/net/gazeplay/commons/utils/ConfigurationDisplay.java, gazeplay/src/main/java/net/gazeplay/commons/utils/Portrait.java, gazeplay/src/main/java/net/gazeplay/games/creampie/CreamPie.java, gazeplay/src/main/java/net/gazeplay/games/creampie/Target.java, gazeplay/src/main/java/net/gazeplay/games/ninja/Ninja.java, gazeplay/src/main/java/net/gazeplay/games/ninja/Target.java
A bunch of improvements in different places of the code.
- some trivial code improvements
- some other bigger changes, mainly in the Ninja games animations. 
The Ninja game was really slow on my computer. 
Now it's better, but I still get bad performance in full screen (maybe because I use a high resolution screen) after the second round of the game.
I could split this in multiple pull requests, but it's really time consuming, so will do it only if needed.
=> Various code improvements

gazeplay/src/main/java/net/gazeplay/games/draw/ColorPicker.java, gazeplay/src/main/java/net/gazeplay/games/draw/DrawApplication.java, gazeplay/src/main/java/net/gazeplay/games/draw/DrawBuilder.java, gazeplay/src/main/java/net/gazeplay/games/draw/ProgressiveColorPicker.java, gazeplay/src/main/java/net/gazeplay/games/draw/RainbowColorPicker.java, gazeplay/src/main/java/net/gazeplay/games/draw/RandomColorPicker.java, gazeplay/src/main/java/net/gazeplay/games/drawonvideo/VideoPlayerWithLiveFeedbackApp.java, gazeplay/src/main/java/net/gazeplay/games/video/VideoPlayerApp.java
added a new Drawing Application 
and a new Video Player with Drawing feature providing live feedback of the gaze location
I hope you'll like it.
This is just a beginning.
=> Drawing Game + Video Player with live feedback of the gaze location

gazeplay-commons/src/main/java/net/gazeplay/commons/gaze/GazeUtils.java, gazeplay/src/main/java/net/gazeplay/commons/utils/multilinguism/LocalMultilinguism.java, gazeplay/src/main/java/net/gazeplay/games/whereisit/WhereIsIt.java
Before commit, you should run a mvn build in order to reformat the code according to the project coding standards. (allowing to get minimal diff in commits)
=> reformat code, as done automatically but the maven plugin

gazeplay-dist/descriptor.xml
fixed missing lib directory containing all of the JARs, in the dist artifact
=> fixed missing lib directory containing all of the JARs, in the dist artifact

gazeplay/src/main/java/net/gazeplay/GameContext.java, gazeplay/src/main/java/net/gazeplay/HomeMenuScreen.java, gazeplay/src/main/java/net/gazeplay/commons/utils/ControlPanelConfigurator.java
=> margins and spacing on the control panel of the home screen

gazeplay/src/main/java/net/gazeplay/commons/utils/stats/StatsDisplay.java
but only preserve ratio for ImageView, not for LineChart for the moment, as it looks better to me
Should fix issue #152
=> added support for preserving ratio in Stats on zoom

gazeplay/src/main/java/net/gazeplay/ConfigurationContext.java, gazeplay/src/main/java/net/gazeplay/HomeMenuScreen.java, gazeplay/src/main/java/net/gazeplay/StatsContext.java
apply control panel layout configuration to the following screens : configuration and statistics
=> Fix for issue #149

gazeplay-commons/src/main/java/net/gazeplay/commons/gaze/devicemanager/AbstractGazeDeviceManager.java
when translating the position to local : 
the gaze position is relative to the screen, 
not relative to the scene, 
so it needs to be translated using the appropriate translation method
=> fixes issue #164 : 

gazeplay/src/main/java/net/gazeplay/GameContext.java, gazeplay/src/main/java/net/gazeplay/GraphicalContext.java, gazeplay/src/main/java/net/gazeplay/HomeMenuScreen.java
=> Add full screen toggle button on home screen

gazeplay-commons/src/main/java/net/gazeplay/commons/gaze/devicemanager/AbstractGazeDeviceManager.java
=> fixed NPE : fixing issue #199

gazeplay/src/main/java/net/gazeplay/games/biboules/Biboule.java
Hand with magic wand added, still the magic effect has to be added.
=> Begining of the magic wand

gazeplay-data/src/main/resources/data/stylesheets/base.css, gazeplay-data/src/main/resources/data/stylesheets/main-blue.css, gazeplay-data/src/main/resources/data/stylesheets/main-green.css, gazeplay-data/src/main/resources/data/stylesheets/main-light-blue.css, gazeplay-data/src/main/resources/data/stylesheets/main-orange.css, gazeplay-data/src/main/resources/data/stylesheets/main-pink-purple.css, gazeplay-data/src/main/resources/data/stylesheets/main-silver-gold.css
Refactoring css files so all common rules are in base.css.
=> Fix ussue#191

gazeplay-commons/src/main/java/net/gazeplay/commons/configuration/Configuration.java, gazeplay-commons/src/main/java/net/gazeplay/commons/configuration/ConfigurationBuilder.java, gazeplay-data/src/main/resources/data/multilinguism/multilinguism.csv, gazeplay/src/main/java/net/gazeplay/ConfigurationContext.java, gazeplay/src/main/java/net/gazeplay/GameContext.java, gazeplay/src/main/java/net/gazeplay/GazePlay.java, gazeplay/src/main/java/net/gazeplay/commons/utils/Bravo.java
Added a checkbox in configuration screen to enable/disable bravo sound effect
=> Fix issue#111

gazeplay-data/src/main/resources/data/stylesheets/base.css, gazeplay-data/src/main/resources/data/stylesheets/main-blue.css, gazeplay-data/src/main/resources/data/stylesheets/main-green.css, gazeplay-data/src/main/resources/data/stylesheets/main-light-blue.css, gazeplay-data/src/main/resources/data/stylesheets/main-orange.css, gazeplay-data/src/main/resources/data/stylesheets/main-pink-purple.css, gazeplay-data/src/main/resources/data/stylesheets/main-silver-gold.css
CSS files that have the same function should use the exact same formatting and have the exact same classes inside.
=> Comparable CSS files

gazeplay/src/main/java/net/gazeplay/HomeMenuScreen.java
remove game chooser's ChoiceBox
in favor of the new large button game chooser
=> remove game chooser's ChoiceBox

gazeplay/src/main/java/net/gazeplay/GazePlay.java, gazeplay/src/main/java/net/gazeplay/HomeMenuScreen.java, gazeplay/src/main/java/net/gazeplay/games/biboules/Biboule.java
Also while i was trying to solve the issue i added a toogleMaximized function to GazePlay. I do not use it but it works. Should i keep it ?
For the Biboule file, i guess it's Maven that has reformatted it.
=> Fixed issue #206. 

gazeplay/src/main/java/net/gazeplay/GazePlay.java
Deleted some unused code introduced with my last pull request
=> Fixed some unused code as asked

gazeplay/src/main/java/net/gazeplay/DefaultGamesLocator.java, gazeplay/src/main/java/net/gazeplay/games/divisor/Divisor.java, gazeplay/src/main/java/net/gazeplay/games/divisor/DivisorStats.java, gazeplay/src/main/java/net/gazeplay/games/divisor/Target.java
I started implementing my game idea : Divisor.
I only created the class and added it the list of games, it does nothing as I don't launch the animation because it's not working as intended yet.
=> Game : Divisor

gazeplay/src/main/java/net/gazeplay/DefaultGamesLocator.java, gazeplay/src/main/java/net/gazeplay/games/memory/Memory.java
The game variant 3x3 is just invalid, as the game expects the total number of card is an even number.
=> Fix issue #233

gazeplay-commons/findbugs-exclude.xml, gazeplay-commons/src/main/java/net/gazeplay/commons/utils/games/Utils.java, gazeplay-commons/src/main/java/net/gazeplay/commons/utils/stats/Stats.java, gazeplay-side-projects/findbugs-exclude.xml, gazeplay-side-projects/src/main/java/utils/arduino/ArduinoSerialCommunication.java, gazeplay/findbugs-exclude.xml, gazeplay/src/main/java/net/gazeplay/GameContext.java, gazeplay/src/main/java/net/gazeplay/GazePlay.java, gazeplay/src/main/java/net/gazeplay/commons/utils/License.java, gazeplay/src/main/java/net/gazeplay/commons/utils/multilinguism/I18N.java, gazeplay/src/main/java/net/gazeplay/commons/utils/stats/HiddenItemsGamesStats.java, gazeplay/src/main/java/net/gazeplay/commons/utils/stats/ShootGamesStats.java, gazeplay/src/main/java/net/gazeplay/games/cups/CupsAndBalls.java, pom.xml
findbugs : remove global exclusions and fix errors raised by findbugs
Only a few exceptions are allowed
=> findbugs hardening

.travis.yml
so that we receive an alert when a PR is not using a clean formatting
=> validate the code formatting in Travis CI

.gitignore, gazeplay-commons/src/main/java/net/gazeplay/commons/utils/games/Utils.java, gazeplay/src/main/java/net/gazeplay/HomeMenuScreen.java
=> DO NOT MERGE YET : introduce background music

.gitignore, gazeplay-commons/src/main/java/net/gazeplay/commons/utils/games/Utils.java, gazeplay/src/main/java/net/gazeplay/HomeMenuScreen.java
Reverts schwabdidier/GazePlay#249
=> Revert "DO NOT MERGE YET : introduce background music"

.gitignore, gazeplay-commons/src/main/java/net/gazeplay/commons/utils/games/Utils.java, gazeplay/src/main/java/net/gazeplay/HomeMenuScreen.java
Play a background music in the main menu.
The background music interrupts when exit the main menu.
I think you can merge.
=> Background music interruptible

gazeplay/src/main/java/net/gazeplay/DefaultGamesLocator.java, gazeplay/src/main/java/net/gazeplay/GameContext.java, gazeplay/src/main/java/net/gazeplay/GameSummary.java, gazeplay/src/main/java/net/gazeplay/GraphicalContext.java, gazeplay/src/main/java/net/gazeplay/HomeMenuScreen.java
introduced a background music in follwing games for the moment
* biboule
* robots 
Please change the music if the one I picked does not suit you
=> added support for a background music per game

gazeplay/src/main/java/net/gazeplay/DefaultGamesLocator.java, gazeplay/src/main/java/net/gazeplay/games/divisor/Divisor.java, gazeplay/src/main/java/net/gazeplay/games/divisor/Target.java
In this version you are able to divide the bubble if the mouse (or gaze) enter it. I need to include time score and add settings, as well as adding a victory screen.
=> Mouse and gaze event working

gazeplay/src/main/java/net/gazeplay/games/divisor/Divisor.java, gazeplay/src/main/java/net/gazeplay/games/divisor/Target.java
I added a victory animation with a time based score, and the game reload automatically. For the transition when a bubble is divised, I'm going to change it so that it'll be prettier and smoother.
=> Fixing issues on Divisor

gazeplay-commons/src/main/java/net/gazeplay/commons/configuration/ConfigurationBuilder.java, gazeplay/src/main/java/net/gazeplay/ConfigurationContext.java, gazeplay/src/main/java/net/gazeplay/DefaultGamesLocator.java, gazeplay/src/main/java/net/gazeplay/games/cups/Ball.java, gazeplay/src/main/java/net/gazeplay/games/cups/Cup.java, gazeplay/src/main/java/net/gazeplay/games/cups/CupsAndBalls.java, gazeplay/src/main/java/net/gazeplay/games/cups/utils/Action.java, gazeplay/src/main/java/net/gazeplay/games/cups/utils/PositionCup.java, gazeplay/src/main/java/net/gazeplay/games/cups/utils/Strategy.java, gazeplay/src/main/java/net/gazeplay/games/draw/DrawApplication.java, gazeplay/src/main/java/net/gazeplay/games/room/Room.java, gazeplay/src/main/java/net/gazeplay/games/room/RoomStats.java
Last pull request got canceled because of the master branch being renamed into the feature/theRoom branch
Things to add to the "Room" game :
1. Add a gazeEventListener
2. Draw and add room walls (textures)
3. Add multilinguism
Things that were changed in the "Cups and Balls" game :
1. Made some attributes final
2. Modified the EventListener declarations into lambda expressions
=> Added alpha version of "Room" game/Modified "Cups and Balls" game

gazeplay/src/main/java/net/gazeplay/games/divisor/Target.java
Using a timeline animation for smoother, continuous movement. Also prepared the "explosion" animation, the white circle will be replaced by an image.
=> Changed animation

gazeplay/src/main/java/net/gazeplay/games/memory/Memory.java, gazeplay/src/main/java/net/gazeplay/games/memory/MemoryCard.java, gazeplay/src/main/java/net/gazeplay/games/openmemory/OpenMemory.java, gazeplay/src/main/java/net/gazeplay/games/openmemory/OpenMemoryCard.java
Now, If there is not enough images in the magiccard folder, the number of images is completed with default images.
=> Images of the folder complete with default images

gazeplay/src/main/java/net/gazeplay/commons/utils/Position.java, gazeplay/src/main/java/net/gazeplay/games/divisor/Target.java, gazeplay/src/main/java/net/gazeplay/games/draw/DrawApplication.java, gazeplay/src/main/java/net/gazeplay/games/draw/DrawBuilder.java, gazeplay/src/main/java/net/gazeplay/games/memory/MemoryCard.java, gazeplay/src/main/java/net/gazeplay/games/openmemory/OpenMemoryCard.java, gazeplay/src/main/java/net/gazeplay/games/shooter/Shooter.java
Scribble works in full screen (some problem of events coordinates when run in a window)
=> version 1.3 scribble works

gazeplay/src/main/java/net/gazeplay/games/divisor/Target.java
Target could be stuck in the menu bar at the bottom, it's fixed.
I also started working on my other game idea. I know it's not validated but it can be adapted to another game if you don't like my Follow the path idea.
=> Fixed collision issue

gazeplay/src/main/java/net/gazeplay/games/divisor/Target.java
Fixed #320 and reduced invincibility frame.
=> Fixed issue #320

gazeplay/src/main/java/net/gazeplay/DefaultGamesLocator.java, gazeplay/src/main/java/net/gazeplay/games/order/Order.java, gazeplay/src/main/java/net/gazeplay/games/order/OrderStats.java, gazeplay/src/main/java/net/gazeplay/games/order/Spawner.java, gazeplay/src/main/java/net/gazeplay/games/order/Target.java
Prepared the class and structure I'll need for the game and started developing it.
=> Started working on Order

gazeplay/src/main/java/net/gazeplay/games/divisor/Target.java, gazeplay/src/main/java/net/gazeplay/games/order/Order.java, gazeplay/src/main/java/net/gazeplay/games/order/Spawner.java, gazeplay/src/main/java/net/gazeplay/games/order/Target.java
Target spawn with a timer, the enter event is handled but need a progress bar.
=> Working on Order

gazeplay/src/main/java/net/gazeplay/games/moles/Moles.java, gazeplay/src/main/java/net/gazeplay/games/moles/MolesChar.java
Both commit are the same : The first one is just without "mvn clean install", I have forgotten it.
=> advancement of the game "Whack the moles"

gazeplay/src/main/java/net/gazeplay/GameContext.java, gazeplay/src/main/java/net/gazeplay/games/cakes/cakeFactory.java
comment of the lines leading to a rectangle bounds error, I will fix it soon, and improvement of the cake factory
=> rectanglebounds error + cakeFactory

gazeplay/src/main/java/net/gazeplay/DefaultGamesLocator.java, gazeplay/src/main/java/net/gazeplay/GameSpec.java, gazeplay/src/main/java/net/gazeplay/games/cakes/cakeFactory.java
3 different modes: free, normal and extreme
=> Cake factory new game modes

gazeplay/src/main/java/net/gazeplay/games/cakes/cakeFactory.java, gazeplay/src/main/java/net/gazeplay/games/cakes/progessButton.java
new modes + creation of the progressButton class that will be used for gazeEvent
=> New Modes / New Events

gazeplay-commons/src/main/java/net/gazeplay/commons/ui/I18NButton.java, gazeplay-commons/src/main/java/net/gazeplay/commons/ui/ProgressButton.java, gazeplay/src/main/java/net/gazeplay/GameContext.java, gazeplay/src/main/java/net/gazeplay/GameMenuFactory.java, gazeplay/src/main/java/net/gazeplay/GraphicalContext.java, gazeplay/src/main/java/net/gazeplay/HomeMenuScreen.java, gazeplay/src/main/java/net/gazeplay/commons/utils/ProgressButton.java, gazeplay/src/main/java/net/gazeplay/commons/utils/ProgressCustomButton.java, gazeplay/src/main/java/net/gazeplay/commons/utils/ProgressHomeButton.java, gazeplay/src/main/java/net/gazeplay/commons/utils/ProgressPane.java, gazeplay/src/main/java/net/gazeplay/commons/utils/stats/StatsDisplay.java, gazeplay/src/main/java/net/gazeplay/games/cakes/cakeFactory.java
Creation of the general progress buttons.
Note: 
-Indicator not displayed yet
-duplicated class ProgressButton in gazeplay-common
=> General Progress Button 

gazeplay/src/main/java/net/gazeplay/ConfigurationContext.java, gazeplay/src/main/java/net/gazeplay/GameContext.java, gazeplay/src/main/java/net/gazeplay/games/room/Room.java
=> Adding a solution for the unseen south arrow in room game and a scroll bar for the configuration menu

gazeplay-commons/src/main/java/net/gazeplay/commons/ui/I18NButton.java, gazeplay-commons/src/main/java/net/gazeplay/commons/ui/ProgressButton.java, gazeplay/src/main/java/net/gazeplay/GameContext.java, gazeplay/src/main/java/net/gazeplay/GameMenuFactory.java, gazeplay/src/main/java/net/gazeplay/GraphicalContext.java, gazeplay/src/main/java/net/gazeplay/HomeMenuScreen.java, gazeplay/src/main/java/net/gazeplay/StatsContext.java, gazeplay/src/main/java/net/gazeplay/commons/utils/ProgressButton.java, gazeplay/src/main/java/net/gazeplay/commons/utils/ProgressCustomButton.java, gazeplay/src/main/java/net/gazeplay/commons/utils/ProgressHomeButton.java, gazeplay/src/main/java/net/gazeplay/commons/utils/ProgressPane.java, gazeplay/src/main/java/net/gazeplay/commons/utils/stats/StatsDisplay.java, gazeplay/src/main/java/net/gazeplay/games/cakes/cakeFactory.java
I used a stack pane containing a button and a progress indicator to create a progressButton. I hope it will not be too heavy for the platform ?
We need to create a generic class for the progress buttons because for now there is a lot of duplicated code.
=> /!\ Big update on most of the classes: progressButtons instead of basic buttons for all the menu !

gazeplay-commons/src/main/java/net/gazeplay/commons/ui/ProgressButton.java, gazeplay-data/src/main/resources/data/multilinguism/multilinguism.csv, gazeplay/src/main/java/net/gazeplay/GameMenuFactory.java, gazeplay/src/main/java/net/gazeplay/commons/utils/ProgressButton.java, gazeplay/src/main/java/net/gazeplay/commons/utils/ProgressCustomButton.java, gazeplay/src/main/java/net/gazeplay/commons/utils/ProgressHomeButton.java, gazeplay/src/main/java/net/gazeplay/commons/utils/ProgressPane.java, gazeplay/src/main/java/net/gazeplay/games/cakes/cakeFactory.java
GameVariant button size improved, and cake factory modification + translation
=> cake factory  & menu improvment

gazeplay-data/src/main/resources/data/multilinguism/multilinguism.csv, gazeplay/src/main/java/net/gazeplay/StatsContext.java, gazeplay/src/main/java/net/gazeplay/games/divisor/Divisor.java, gazeplay/src/main/java/net/gazeplay/games/divisor/Target.java, gazeplay/src/main/java/net/gazeplay/games/order/Order.java, gazeplay/src/main/java/net/gazeplay/games/order/Target.java
Fixed #406 and #394 with the correct translations
Also fixed an issue on Divisor and working on performances
=> Solved issues with translations and improving games

gazeplay-commons/src/main/java/net/gazeplay/commons/configuration/Configuration.java, gazeplay-commons/src/main/java/net/gazeplay/commons/utils/games/BackgroundMusicManager.java, gazeplay-commons/src/main/java/net/gazeplay/commons/utils/games/Utils.java, gazeplay/src/main/java/net/gazeplay/GraphicalContext.java
I remove the know redundant volume property from Background music manager to instead use the one from Configuration. I also added some bindings with the new volumes properties. Finally i added some checks on volume values.
=> added some binding with volums and new config properties

gazeplay-commons/src/main/java/net/gazeplay/commons/configuration/Configuration.java, gazeplay-commons/src/main/java/net/gazeplay/commons/utils/games/BackgroundMusicManager.java, gazeplay-data/src/main/resources/data/multilinguism/multilinguism.csv, gazeplay/src/main/java/net/gazeplay/ConfigurationContext.java, gazeplay/src/main/java/net/gazeplay/GameContext.java, gazeplay/src/main/java/net/gazeplay/GameMenuFactory.java, gazeplay/src/main/java/net/gazeplay/GraphicalContext.java, gazeplay/src/main/java/net/gazeplay/HomeMenuScreen.java
Fixed most of the inconsistency (i hope) between title displayed and music currently playing.
Also added reset button for folder inputs in configuration.
=> Default music

gazeplay/src/main/java/net/gazeplay/games/colors/ColorBox.java, gazeplay/src/main/java/net/gazeplay/games/colors/ColorsGame.java
This PR fixes issue #435.
I moved the tool box to the right of the screen so the configuration button doesn't overlap anymore. I aslo fixed the button styling when selected.
=> Fix config button in color game

gazeplay/src/main/java/net/gazeplay/GameContext.java, gazeplay/src/main/java/net/gazeplay/GraphicalContext.java
Fixed issue #434. Now the panel won't receive any event when hidden. Also fixed a null pointer exception that i had about the music controller
=> Games config panel

gazeplay/src/main/java/net/gazeplay/GameContext.java, gazeplay/src/main/java/net/gazeplay/games/cakes/ProgressButton.java, gazeplay/src/main/java/net/gazeplay/games/cakes/cakeFactory.java
=> issue #434 solved

gazeplay/src/main/java/net/gazeplay/HomeMenuScreen.java
Just a line to show the idea of the issue #448
=> background of the menu

gazeplay-data/src/main/resources/data/multilinguism/multilinguism.csv
I don't know why there is written "72 additions and 71 deletions". I just add the row "Labyrinth".
=> multilinguism for Labyrinth

gazeplay-commons/src/main/java/net/gazeplay/commons/utils/games/Utils.java, gazeplay/src/main/java/net/gazeplay/commons/utils/Bravo.java, gazeplay/src/main/java/net/gazeplay/games/whereisit/WhereIsIt.java
I fixed the sounds that were not found. Using URL from classLoader doesn't seem to work anymore.
=> fixed sound url

gazeplay/src/main/java/net/gazeplay/games/colors/ColorToolBox.java, gazeplay/src/main/java/net/gazeplay/games/colors/ColorsGame.java
Fixed a path to picture in the color game
=> fixed picture path

gazeplay/src/main/java/net/gazeplay/GameContext.java, gazeplay/src/main/java/net/gazeplay/games/cakes/cakeFactory.java, gazeplay/src/main/java/net/gazeplay/games/shooter/Shooter.java
=> Small Modif

gazeplay/src/main/java/net/gazeplay/GameContext.java
solve issue #469 . @kuhlkrein .
=> removing of black bar

gazeplay/src/main/java/net/gazeplay/GraphicalContext.java, gazeplay/src/main/java/net/gazeplay/HomeMenuScreen.java, gazeplay/src/main/java/net/gazeplay/games/pianosight/Jukebox.java, gazeplay/src/main/java/net/gazeplay/games/pianosight/Piano.java
this functions were leading to issues #478 , #436
=> modification of the function using file.separator

gazeplay-commons/src/main/java/net/gazeplay/commons/configuration/Configuration.java, gazeplay-commons/src/main/java/net/gazeplay/commons/gaze/devicemanager/AbstractGazeDeviceManager.java, gazeplay-data/src/main/resources/data/multilinguism/multilinguism.csv, gazeplay/src/main/java/net/gazeplay/ConfigurationContext.java, gazeplay/src/main/java/net/gazeplay/GameButtonPane.java, gazeplay/src/main/java/net/gazeplay/GameMenuFactory.java, gazeplay/src/main/java/net/gazeplay/GazePlay.java, gazeplay/src/main/java/net/gazeplay/HomeMenuScreen.java, gazeplay/src/main/java/net/gazeplay/games/cakes/ProgressButton.java, gazeplay/src/main/java/net/gazeplay/games/cakes/ScreenCake.java, gazeplay/src/main/java/net/gazeplay/games/cakes/cakeFactory.java
Throw some errors so I added the button in configuration panel but is not usable for now, cf buildGazeMenu function in the ConfigurationContext class
=> Beta of the gaze menu

gazeplay-commons/src/main/java/net/gazeplay/commons/gaze/devicemanager/AbstractGazeDeviceManager.java, gazeplay-commons/src/main/java/net/gazeplay/commons/gaze/devicemanager/TobiiGazeDeviceManager.java, gazeplay/src/main/java/net/gazeplay/ConfigurationContext.java, gazeplay/src/main/java/net/gazeplay/GazePlay.java
I change the refresh time of abstractgazedevicemanager to a lower value
so that it will not throw unexpected exeption. 25 instead of 10 seems to
be good. I also tried with 50 but it's maybe a bit too much for some
games
=> Modifications in order to make the gazemenu usable.

gazeplay-commons/src/main/java/net/gazeplay/commons/configuration/Configuration.java, gazeplay/src/main/java/net/gazeplay/ConfigurationContext.java
Correction of the music issue #390 , but it leads to the issue #497
because of the complex way of accessing the folder.
=> Music correction

gazeplay-commons/src/main/java/net/gazeplay/commons/configuration/Configuration.java, gazeplay-commons/src/main/java/net/gazeplay/commons/gaze/devicemanager/GazeDeviceManagerFactory.java, gazeplay-commons/src/main/java/net/gazeplay/commons/gaze/devicemanager/TobiiGazeDeviceManager.java, gazeplay/src/main/java/net/gazeplay/ConfigurationContext.java, gazeplay/src/main/java/net/gazeplay/GazePlay.java
=> Implementation of GazeMouse

gazeplay/src/main/java/net/gazeplay/DefaultGamesLocator.java, gazeplay/src/main/java/net/gazeplay/commons/utils/ProgressButton.java, gazeplay/src/main/java/net/gazeplay/games/cakes/CakeFactory.java, gazeplay/src/main/java/net/gazeplay/games/cakes/ScreenCake.java, gazeplay/src/main/java/net/gazeplay/games/pet/PetHouse.java
Begining of the implementation
=> Implementation of the new game

gazeplay-commons/src/main/java/net/gazeplay/commons/configuration/Configuration.java, gazeplay/src/main/java/net/gazeplay/UserProfilContext.java
works for file folder, picture profile etc...
=> Reading files from folders added manually by user as for default user

gazeplay-commons/src/main/java/net/gazeplay/commons/utils/games/BackgroundMusicManager.java, gazeplay/src/main/java/net/gazeplay/ConfigurationContext.java, gazeplay/src/main/java/net/gazeplay/UserProfilContext.java
=> Modifications for music and music volume slider

gazeplay-commons/src/main/java/net/gazeplay/commons/gaze/devicemanager/AbstractGazeDeviceManager.java, gazeplay/src/main/java/net/gazeplay/GraphicalContext.java, gazeplay/src/main/java/net/gazeplay/commons/utils/ProgressButton.java, gazeplay/src/main/java/net/gazeplay/games/cakes/CakeFactory.java, gazeplay/src/main/java/net/gazeplay/games/ninja/Ninja.java, gazeplay/src/main/java/net/gazeplay/games/ninja/Target.java
plus trying to see if we can gain some space when exiting some games
(Ninja)
=> Correction of the gaze evt for buttons in pet and cake games

gazeplay-commons/src/main/java/net/gazeplay/commons/gaze/devicemanager/AbstractGazeDeviceManager.java, gazeplay-commons/src/main/java/net/gazeplay/commons/gaze/devicemanager/GazeInfos.java, gazeplay-commons/src/main/java/net/gazeplay/commons/gaze/devicemanager/TobiiGazeDeviceManager.java, gazeplay/src/main/java/net/gazeplay/games/mediaPlayer/GazeMediaPlayer.java, gazeplay/src/main/java/net/gazeplay/games/mediaPlayer/MediaFile.java, gazeplay/src/main/java/net/gazeplay/games/mediaPlayer/MediaFileReader.java, gazeplay/src/main/java/net/gazeplay/games/shooter/Shooter.java
addition and deletion recursive
=> modification of the gaze device manager

gazeplay/src/main/java/net/gazeplay/games/rushHour/Car.java, gazeplay/src/main/java/net/gazeplay/games/rushHour/RushHour.java
=> Rush Hour game 

gazeplay/src/main/java/net/gazeplay/UserProfilContext.java, gazeplay/src/main/java/net/gazeplay/commons/utils/ProgressButton.java, gazeplay/src/main/java/net/gazeplay/games/pet/Mypet.java, gazeplay/src/main/java/net/gazeplay/games/pet/PetHouse.java, gazeplay/src/main/java/net/gazeplay/games/rushHour/Car.java, gazeplay/src/main/java/net/gazeplay/games/rushHour/RushHour.java
various Improvements in pet and rushhour games
+ copy images when creating/modifying profile , issue #565
=> rushHour & pet modif

gazeplay-commons/src/main/java/net/gazeplay/commons/utils/multilinguism/Multilinguism.java, gazeplay-data/src/main/resources/data/multilinguism/multilinguism.csv, gazeplay/src/main/java/net/gazeplay/ConfigurationContext.java, gazeplay/src/main/java/net/gazeplay/UserProfilContext.java
=> Problem fixed with the reset button in configContext

gazeplay-commons/pom.xml, gazeplay-data/pom.xml, gazeplay-dist/pom.xml, gazeplay-melordi/pom.xml, gazeplay-picto-pick/pom.xml, gazeplay-side-projects/pom.xml, gazeplay/pom.xml, gazeplay/src/main/java/net/gazeplay/ConfigurationContext.java, pom.xml
This reverts commit e552712ffde0a71e093094eff940845221883535.
Fix issue #594
=> Fix issue #594

gazeplay-commons/src/main/java/net/gazeplay/commons/utils/HeatMap.java
I removed the transparent aspect of the heatmap, in response to #627
=> Heat Map: Removed transparent colors and background

gazeplay/src/main/java/net/gazeplay/games/rushHour/RushHour.java
I haven't implemented a level selection menu and the score but I think there should be these features. There are now 33 levels.
=> New levels in RushHour, without a menu of level selection and the score

gazeplay-data/src/main/resources/data/multilinguism/multilinguism.csv, gazeplay/src/main/java/net/gazeplay/games/race/Race.java
This commit changes the titles for ribbit race in French and has a minor change in the spawn location of biboules in ribbit race. [TRAVIS VALIDATED]
=> Language for race

gazeplay-commons/src/main/java/net/gazeplay/commons/utils/HeatMap.java
Quick heat map patch, in response to #705 
I suspect the error to only happen on very specific values, since I wasn't able to recreate the error.
So I modified the code a little bit so it should never fetch a value outside the array bounds.
=> Heatmap patch

gazeplay-commons/src/main/java/net/gazeplay/commons/utils/HeatMap.java, gazeplay-commons/src/main/java/net/gazeplay/commons/utils/stats/SavedStatsInfo.java, gazeplay-commons/src/main/java/net/gazeplay/commons/utils/stats/Stats.java, gazeplay/src/main/java/net/gazeplay/StatsContext.java, gazeplay/src/main/java/net/gazeplay/commons/utils/stats/StatsDisplay.java
Issue #743 
I added a screenshot as a background to the heatmap and fixation points.
I had to go a different route than the way the heatmap and fixation points were combined before, since the screenshot and the heatmap image are not the same dimensions, merging them doesn't work.
So I had to improvise and stack the different components as layers in a StackPane.
I also modified the heatmap, the background is now transparent, and the colors have 0.8 alpha.
=> Image behind heatmap

Games-eng.md, gazeplay/src/main/java/net/gazeplay/AreaOfInterest.java, gazeplay/src/main/java/net/gazeplay/StatsContext.java
Improvements and fixes to the AOI and added Ribbit Race to GAME.MD (#761)
=> Aoi improvements

Games-eng.md, Games-fra.md, gazeplay-commons/src/main/java/net/gazeplay/commons/utils/FixationSequence.java, gazeplay-commons/src/main/java/net/gazeplay/commons/utils/stats/Stats.java
the merge conflict was not well resolved and therefore inferred problems in the output of the fixation Sequence
=> fixed a previous conflict between AOI and fixation sequence

gazeplay/src/main/java/net/gazeplay/games/space/SpaceGame.java
I have made some adjustments to the control of the spaceship and ensure some problem with memory when the game lasts long.
=> Space Game improving controlling mechanism of the spaceship

Games-eng.md, Games-fra.md, gazeplay-commons/src/main/java/net/gazeplay/commons/configuration/Configuration.java, gazeplay/src/main/java/net/gazeplay/GameContext.java, gazeplay/src/main/java/net/gazeplay/GameMenuFactory.java, gazeplay/src/main/java/net/gazeplay/GraphicalContext.java, gazeplay/src/main/java/net/gazeplay/HomeMenuScreen.java, gazeplay/src/main/java/net/gazeplay/commons/utils/stats/StatsDisplay.java, gazeplay/src/main/java/net/gazeplay/games/bubbles/Bubble.java, gazeplay/src/main/java/net/gazeplay/games/ninja/Ninja.java
Instead of using +/- keys like in the initial idea , I used **F** (fast )and **S** ( slow) keys. I did so because the + and - keys from the Numpad were not firing Events [an issue I could try and resolve in the future], furthermore some laptops are not equipped with a numpad and the combination of _Shift + "="_  to make a plus would not be practical .
=> Change speed effect using the keyboard

gazeplay/src/main/java/net/gazeplay/games/biboulejump/BibouleJump.java, gazeplay/src/main/java/net/gazeplay/games/goosegame/GooseGame.java, gazeplay/src/main/java/net/gazeplay/games/spotthedifferences/SpotTheDifferences.java
I am not able to test if this fixes the problem, since I wasn't encountering it in the first place.
This works on my PC.
=> Possible fix for file system errors

gazeplay-commons/src/main/java/net/gazeplay/commons/configuration/Configuration.java, gazeplay/src/main/java/net/gazeplay/ConfigurationContext.java
- Max number of colors set to 7
- Buttons are disabled when not applicable
- Reset button
In response to #817 and #818
=> Heat map configuration tweaking

gazeplay/src/main/java/net/gazeplay/HomeMenuScreen.java
=> Fixed inconsistency with checkbox selections

gazeplay-commons/src/main/java/net/gazeplay/commons/utils/games/Utils.java, gazeplay/src/main/java/net/gazeplay/DefaultGamesLocator.java, gazeplay/src/main/java/net/gazeplay/GameContext.java, gazeplay/src/main/java/net/gazeplay/GameMenuFactory.java, gazeplay/src/main/java/net/gazeplay/commons/utils/Bravo.java, gazeplay/src/main/java/net/gazeplay/games/space/SpaceGame.java
Interrupt sound on Game Exit / #809
=> Small sound fix 

Games-eng.md, Games-fra.md
The last 4 games have no description . I am not sure on what to write as I do not fully understand what these games do .
=> All Games present / #761

gazeplay-commons/src/main/java/net/gazeplay/commons/utils/multilinguism/LanguageDetails.java, gazeplay-commons/src/main/java/net/gazeplay/commons/utils/multilinguism/Languages.java, gazeplay/src/main/java/net/gazeplay/ConfigurationContext.java
Improvements on the languages definitions
in order to cleanup the code
=> improvements on Languages definitions

gazeplay-games/src/main/java/net/gazeplay/games/biboulejump/BibouleJump.java, gazeplay-games/src/main/java/net/gazeplay/games/biboulejump/MovingPlatform.java, gazeplay-games/src/main/java/net/gazeplay/games/biboulejump/Platform.java, gazeplay-games/src/main/java/net/gazeplay/games/goosegame/GooseGame.java, gazeplay-games/src/main/java/net/gazeplay/games/goosegame/Pawn.java
- improve code quality
- added speed adjust to goose game
=> Animation speed ratio improvements

gazeplay-games/src/main/java/net/gazeplay/games/blocs/Blocs.java, gazeplay-games/src/main/java/net/gazeplay/games/cakes/CakeFactory.java, gazeplay-games/src/main/java/net/gazeplay/games/colors/ColorBox.java, gazeplay-games/src/main/java/net/gazeplay/games/colors/ColorToolBox.java, gazeplay-games/src/main/java/net/gazeplay/games/colors/ColorsGame.java, gazeplay-games/src/main/java/net/gazeplay/games/colors/CustomColorPicker.java, gazeplay-games/src/main/java/net/gazeplay/games/colors/GazeFollowerIndicator.java, gazeplay-games/src/main/java/net/gazeplay/games/literacy/Letters.java, gazeplay-games/src/main/java/net/gazeplay/games/slidingpuzzle/SlidingPuzzleCard.java, gazeplay/src/main/java/net/gazeplay/ui/scenes/gamemenu/GameMenuFactory.java, gazeplay/src/main/java/net/gazeplay/ui/scenes/stats/StatsContext.java
=> Fixing issues for next release

gazeplay-games/src/main/java/net/gazeplay/games/bubbles/Bubble.java, gazeplay-games/src/main/java/net/gazeplay/games/bubbles/BubbleGameVariantGenerator.java, gazeplay-games/src/main/java/net/gazeplay/games/bubbles/BubblesGameVariant.java, gazeplay-games/src/main/java/net/gazeplay/games/bubbles/ColoredBubblesGameLauncher.java, gazeplay-games/src/main/java/net/gazeplay/games/bubbles/ColoredBubblesGameSpecSource.java, gazeplay-games/src/main/java/net/gazeplay/games/bubbles/PortraitBubblesGameLauncher.java, gazeplay-games/src/main/java/net/gazeplay/games/bubbles/PortraitsBubblesGameSpecSource.java, gazeplay-games/src/main/java/net/gazeplay/games/whereisit/PictureCard.java, gazeplay-games/src/main/java/net/gazeplay/games/whereisit/WhereIsIt.java, gazeplay/src/main/java/net/gazeplay/ui/scenes/ingame/GameContextFactoryBean.java
Bubble game variant: #933  
+ quick fix for Find the Odd one out issue #955,
But need to solve #962  for definitive fix
=> #933  + quick fix for #955 

gazeplay-commons/src/main/java/net/gazeplay/commons/gaze/Test.java, gazeplay-commons/src/main/java/net/gazeplay/commons/gaze/devicemanager/AbstractGazeDeviceManager.java, gazeplay-commons/src/main/java/net/gazeplay/commons/gaze/devicemanager/GazeDeviceManagerFactory.java, gazeplay-commons/src/main/java/net/gazeplay/commons/gaze/devicemanager/PositionPollerRunnable.java, gazeplay-commons/src/main/java/net/gazeplay/commons/gaze/devicemanager/TobiiGazeDeviceManager.java, gazeplay-commons/src/main/java/net/gazeplay/commons/utils/CachingSupplier.java, gazeplay-commons/src/main/java/net/gazeplay/commons/utils/RobotSupplier.java, gazeplay-commons/src/main/java/net/gazeplay/commons/utils/ScreenDimensionSupplier.java, gazeplay-picto-pick/src/main/java/pictogrammes/Pictogrammes.java, gazeplay-side-projects/src/main/java/arduino/windmill/WindMill.java, gazeplay/src/main/java/net/gazeplay/SpringApplication.java, gazeplay/src/main/java/net/gazeplay/ui/scenes/gamemenu/HomeMenuScreenFactoryBean.java, gazeplay/src/main/java/net/gazeplay/ui/scenes/ingame/GameContextFactoryBean.java
Postpone screen size detection (done using JavaFX) to actual moment of first use (so that this is only done after JavaFX was initialized)  + AWT Robot can only be created once
=> Fix JavaFX use before JavaFX initialization

.github/workflows/gradle.yml
trigger gradle build workflow on pull requests too
in addition to on push to upstream repository
=> trigger gradle build workflow on pull requests too

gazeplay-commons/src/main/java/net/gazeplay/commons/configuration/Configuration.java, gazeplay-games/src/main/java/net/gazeplay/games/colors/ColorToolBox.java, gazeplay-games/src/main/java/net/gazeplay/games/colors/ColorsGame.java
Fix some issues introduced in PR #970
=> Fix after PR #970

gazeplay/spotbugs-exclude.xml, gazeplay/src/main/java/net/gazeplay/ui/scenes/ingame/GameContext.java, gazeplay/src/main/java/net/gazeplay/ui/scenes/ingame/VideoRecordingContext.java, gazeplay/src/test/java/net/gazeplay/ui/scenes/ingame/GameContextTest.java
=> Home Button Fix

CONTRIBUTING.MD, README.md, build.gradle, gradle/integration.gradle
It won't let me squash the commits - there's literally nothing I can do to fix this
=> Testing docs

gazeplay/src/main/java/net/gazeplay/commons/app/LogoFactory.java, gazeplay/src/test/java/net/gazeplay/commons/app/LogoFactoryTest.java
`LogoFactory` _line 31_ - [AvoidThrowingRawExceptionTypes](https://pmd.github.io/latest/pmd_rules_java_design.html#avoidthrowingrawexceptiontypes)
Created an inner class with a custom `RuntimeException` and replaced the existing raw `RuntimeException`.
Added 93% test coverage to the `LogoFactory`
=> PMD Problems - LogoFactory

gazeplay/src/main/java/net/gazeplay/commons/utils/ConfigurationButton.java, gazeplay/src/main/java/net/gazeplay/commons/utils/ConfigurationButtonFactory.java, gazeplay/src/main/java/net/gazeplay/ui/scenes/gamemenu/HomeMenuScreen.java, gazeplay/src/test/java/net/gazeplay/commons/utils/BravoTest.java, gazeplay/src/test/java/net/gazeplay/commons/utils/ConfigurationButtonFactoryTest.java, gazeplay/src/test/java/net/gazeplay/commons/utils/ConfigurationButtonTest.java, pmd-ruleset.xml
`ConfigurationButton` - [ClassWithOnlyPrivateConstructorsShouldBeFinal](https://pmd.github.io/pmd-6.17.0/pmd_rules_java_design.html#classwithonlyprivateconstructorsshouldbefinal)
Made the class final.
* Added 100% test coverage to Configuration Button
* Refined Bravo test, it is now at 10s for the animation, which is the expected length.
=> PMD Problems - ConfigurationButton

gazeplay-commons/build.gradle
Working with linux when drivers are installed.
=> TobiiStreamEngineForJava:3.0 -> TobiiStreamEngineForJava:4.0

gazeplay/src/main/java/net/gazeplay/gameslocator/GameSpecSourceInstantiator.java, gazeplay/src/test/java/net/gazeplay/gameslocator/GameSpecSourceInstantiatorTest.java
`GameSpecSourceInstantiator` - [AvoidThrowingRawExceptions](https://pmd.github.io/pmd-6.17.0/pmd_rules_java_design.html#avoidthrowingrawexceptiontypes)
Implemented custom GameSpecInstantiationException.
100% test coverage
=> PMD Problems - GameSpecSourceInstantiator

build.gradle, gazeplay/src/main/java/net/gazeplay/ui/scenes/stats/AreaOfInterest.java, gazeplay/src/test/java/net/gazeplay/ui/scenes/stats/AreaOfInterestTest.java, gradle/pmd.gradle
[LocalVariableNamingConventions](https://pmd.github.io/pmd-6.17.0/pmd_rules_java_codestyle.html#localvariablenamingconventions)
Various locations
Changed various names.
Another big changelist:
* Lots of refactoring. Most of the code was clumped together and difficult to read, so I spaced it out. I also reordered some methods so we have general purpose static methods in one block, and related methods at least close by.
* Fixed playback buttons. These now play at the correct speeds, and the scene resets itself after each playback. Cancel button also works.
* Optimisations. Nothing major here, but there were some places where no-ops were happening so I removed those. On a developer machine I couldn't actually measure any difference, but removing unneeded operations is always a best practise. …
=> PMD Problems - AreaOfInterest

gazeplay-commons/src/main/java/net/gazeplay/commons/configuration/observableproperties/ApplicationConfigBackedObjectProperty.java, gazeplay-commons/src/main/java/net/gazeplay/commons/configuration/observableproperties/EnumMarshaller.java, gazeplay-commons/src/main/java/net/gazeplay/commons/configuration/observableproperties/EnumUnmarshaller.java, gazeplay-commons/src/main/java/net/gazeplay/commons/configuration/observableproperties/PropertiesObjectProperty.java
=> introduced ApplicationConfigBackedObjectProperty (that is also applicable to enums)

build.gradle, gazeplay/src/main/java/net/gazeplay/ui/scenes/ingame/GameContext.java, gazeplay/src/main/java/net/gazeplay/ui/scenes/stats/AreaOfInterest.java, gazeplay/src/main/java/net/gazeplay/ui/scenes/stats/ScanpathView.java, gazeplay/src/main/java/net/gazeplay/ui/scenes/stats/StatsContext.java, gazeplay/src/main/java/net/gazeplay/ui/scenes/stats/StatsContextFactory.java, gazeplay/src/test/java/net/gazeplay/ui/scenes/ingame/GameContextTest.java, gazeplay/src/test/java/net/gazeplay/ui/scenes/stats/StatsContextFactoryTest.java, gazeplay/src/test/java/net/gazeplay/ui/scenes/stats/StatsContextTest.java, gradle/pmd.gradle
[LocalVariableNamingConventions](https://pmd.github.io/pmd-6.17.0/pmd_rules_java_codestyle.html#localvariablenamingconventions)
Various locations
[Class with only private contructors should be final](https://pmd.github.io/pmd-6.17.0/pmd_rules_java_design.html#classwithonlyprivateconstructorsshouldbefinal)
`StatsContext` line 40
Changed various names.
Split the class up into a package private class and a public factory.
* Updated JUnit to 5.6.0 to allow for some new tests.
* Refactored a lot of the code, splitting it up a bit more logically.
* 100% test coverage
* PMD checks are now per-module. Previously, it was possible to ADD more violations without being caught, as it was only checking the same thresholds amongst ALL modules. Now we should be safe until we can set a blanket 0 all round
=> PMD Problems - StatsContext

docs/_pages/installation.md, docs/fr/_pages/installation.md
Update web site with AWS Amazon s3 bucket link for advance users and developper on eng and fr installation pages
=> Update web site with s3 download link

GazePlay-1.7.2.md
I let you do other PRs to complete this file with what you solved
=> Adding issues I helped to solve for 1.7.2. (Kuhlkrein)

gazeplay-commons/src/main/java/net/gazeplay/commons/utils/stats/Stats.java, gazeplay-games/src/main/java/net/gazeplay/games/divisor/DivisorStats.java, gazeplay-games/src/main/java/net/gazeplay/games/divisor/Target.java, gazeplay-games/src/main/java/net/gazeplay/games/horses/Horses.java
- Rabit and divisor -> end check boolean changed to avoid ending with still one element on screen
- StatsContext -> x/0 gives 100%, 0/1 gives 0%
- Horse -> display stats at the end and propose a new game
=> Minor quick fixes for 1.7.2

.github/workflows/cd.yml, gradle/installer.gradle
=> Changed permissions for JREs

gazeplay-games/src/main/java/net/gazeplay/games/pet/PetHouse.java
Update of the way we got the height and width of the gamecontext
=> Removing cursor visibility changes

gazeplay/src/main/java/net/gazeplay/ui/scenes/gamemenu/GameMenuController.java
due to custom default music background
=> fix the null pointer error given by biboule and robot games 

gazeplay/src/main/java/net/gazeplay/ui/scenes/stats/ScanpathView.java, gazeplay/src/main/java/net/gazeplay/ui/scenes/stats/StatsContext.java
don't forget to add continue button after coming back from aoi section for games with stats between each play
fix #1154
=> fix continue button on statsContext when coming from AOIContext

gazeplay/src/main/java/net/gazeplay/ui/scenes/gamemenu/HomeMenuScreen.java
The favorite games are now copied on a top section
=> Create a top section for favorite games

gazeplay/src/main/java/net/gazeplay/ui/scenes/gamemenu/HomeMenuScreen.java
Improve favorite game section code to avoid creation of gamecards after each call of the filter game function
=> Improve favorite game section code to avoid creation of gamecards

.github/workflows/ci.yml, .travis.yml, gazeplay-commons/src/main/java/net/gazeplay/commons/utils/games/BackgroundMusicManager.java, gazeplay-commons/src/test/java/net/gazeplay/commons/utils/games/BackgroundMusicManagerTest.java, gazeplay/src/test/java/net/gazeplay/ui/MusicControlTest.java
Fixes #1157. Also made music tests run in CI.
=> Caching to User Folder due to permissioning errors

gazeplay-commons/src/main/java/net/gazeplay/commons/utils/stats/Stats.java, gazeplay-commons/src/test/java/net/gazeplay/commons/utils/stats/StatsTest.java, gradle/pmd.gradle, pmd-ruleset.xml
`Stats` 
[FormalParameterNamingConventions](https://pmd.github.io/pmd-6.17.0/pmd_rules_java_codestyle.html#formalparameternamingconventions)
Changed variable names
* 78% test coverage
=> PMD Problems - Stats

gazeplay-games/src/main/java/net/gazeplay/games/space/SpaceGame.java
-remove the unused code.
-Ship's stable, no more jumps between two positions.
-The ship's in the right place even if we resize and go into window mode.
-The number of Biboules has been reduced from 15 to 10, you also have to kill them all to make the next group appear.
-Biboules remain in the screen now.
=> space game updates

gazeplay-games/src/main/java/net/gazeplay/games/race/Race.java
Places the score at the top left of the game
=> Score place change

gradle/installer.gradle
A long needed fix left over from when I changed `gazeplay` to `gazeplay-core`
=> Fixing Innosetup file setup

gazeplay-games/src/main/java/net/gazeplay/games/space/SpaceGame.java
Update :
- Boss is now in the game
- adjustable attack speed
- the ship's hitbox is according to the ship.
=> Updates space game

gazeplay-games/src/main/java/net/gazeplay/games/bottle/BottleGameLauncher.java, gazeplay-games/src/main/java/net/gazeplay/games/bottle/BottleGameVariantGenerator.java, gazeplay-games/src/main/java/net/gazeplay/games/opinions/OpinionsGameLauncher.java, gazeplay-games/src/main/java/net/gazeplay/games/paperScissorsStone/PaperScissorsStoneLauncher.java
Not sure how, but CI missed these classes and broke `develop`. Build runs fine locally, hopefully this will be the last of these issues.
=> Refactor + Bug Fix - Game Variants

gazeplay-commons/src/main/java/net/gazeplay/commons/configuration/Configuration.java, gazeplay-core/src/main/java/net/gazeplay/ui/scenes/configuration/ConfigurationContext.java, gazeplay-core/src/main/resources/data/multilinguism/multilinguism.csv, gazeplay-core/src/test/java/net/gazeplay/ui/scenes/configuration/ConfigurationContextTest.java, gazeplay-games/src/main/java/net/gazeplay/games/whereisit/PictureCard.java, gradle.properties
=> Reask question on fail option

gazeplay-commons/src/main/java/net/gazeplay/commons/utils/stats/Stats.java, gazeplay-core/src/main/java/net/gazeplay/ui/scenes/configuration/ConfigurationContext.java, gazeplay-games/src/main/java/net/gazeplay/games/bottle/BottleGame.java
=> bottle automatic position on both shelf

gazeplay-commons/src/main/java/net/gazeplay/commons/configuration/Configuration.java, gazeplay-commons/src/main/java/net/gazeplay/commons/gaze/devicemanager/AbstractGazeDeviceManager.java, gazeplay-commons/src/main/java/net/gazeplay/commons/gaze/devicemanager/PositionPollerRunnable.java, gazeplay-commons/src/main/java/net/gazeplay/commons/utils/stats/Stats.java, gazeplay-commons/src/test/java/net/gazeplay/commons/configuration/ConfigurationTest.java, gazeplay-core/src/main/java/net/gazeplay/GazePlay.java, gazeplay-core/src/main/java/net/gazeplay/GazePlayFxApp.java, gazeplay-core/src/main/java/net/gazeplay/ReplayingGameFromJson.java, gazeplay-core/src/main/java/net/gazeplay/commons/utils/stats/StatDisplayUtils.java, gazeplay-core/src/main/java/net/gazeplay/ui/scenes/configuration/ConfigurationContext.java, gazeplay-core/src/main/java/net/gazeplay/ui/scenes/gamemenu/GameMenuController.java, gazeplay-core/src/main/java/net/gazeplay/ui/scenes/gamemenu/HomeMenuScreen.java, gazeplay-core/src/main/java/net/gazeplay/ui/scenes/gamemenu/HomeMenuScreenFactoryBean.java, gazeplay-core/src/test/java/net/gazeplay/commons/utils/stats/StatDisplayUtilsTest.java, gazeplay-core/src/test/java/net/gazeplay/ui/scenes/configuration/ConfigurationContextTest.java, gazeplay-games/src/main/java/net/gazeplay/games/bottle/BottleGame.java, gazeplay-games/src/main/java/net/gazeplay/games/magicpotions/Potion.java
avoid dll issue when using eye tracker on windows with new "one jvm per game" implementation
=> Jvm menu in brackground + fix for bottle and magicpotion

gazeplay-games/src/main/java/net/gazeplay/games/bottle/BottleGameVariantGenerator.java
=> adding 12 bottles game variant

_data/navigation.yml, _pages/references.md, fr/_pages/references.md, index-fr.md, index.md
As requested in #1270
Also updates the version numbers in the banner, as this was missed during the last update.
I copied the French translation from the Wordpress site, so hopefully it's all ok!
=> Adding References Page

gazeplay-games/src/main/java/net/gazeplay/games/space/SpaceGame.java
I boost the speed of our bullets by 3 ( 3>>1 seconds to browse the screen) issue #1300
=> Space game Issue#1300

gazeplay-games/src/main/java/net/gazeplay/games/ninja/Target.java
Resolve the bug between the first translation and the second in random mode (issue #1337 )
=> resolve the random issue (Issue#1337)

gazeplay-core/src/main/resources/data/multilinguism/multilinguism.csv, gazeplay-games-commons/src/main/java/net/gazeplay/commons/gamevariants/IGameVariant.java, gazeplay-games-commons/src/main/java/net/gazeplay/commons/gamevariants/IntStringGameVariant.java, gazeplay-games-commons/src/main/java/net/gazeplay/commons/gamevariants/generators/IntStringListVariantGenerator.java, gazeplay-games/src/main/java/net/gazeplay/games/bottle/BottleGame.java, gazeplay-games/src/main/java/net/gazeplay/games/bottle/BottleGameLauncher.java, gazeplay-games/src/main/java/net/gazeplay/games/bottle/BottleGameVariantGenerator.java
Need a translation with the size name (like small, big ...)
=> Different type of bottles (idea from Jessica Martinez) #1253

gazeplay-games/src/main/java/net/gazeplay/games/cakes/CakeFactory.java, gazeplay-games/src/main/java/net/gazeplay/games/cakes/ScreenCake.java
you don't have a positive result if you not complete the cake in the normale and extreme mode
=> The cake factory, Normal and Extreme level #1297

gazeplay-games/src/main/java/net/gazeplay/games/labyrinth/GameBox.java, gradle.properties
more contrast with the color of the walls
=> Labyrinth Game Visual #1325

gazeplay-core/src/main/java/net/gazeplay/ui/scenes/ingame/GameContext.java, gazeplay-games-commons/src/main/java/net/gazeplay/IGameContext.java, gazeplay-games/src/main/java/net/gazeplay/games/blocs/Blocs.java, gazeplay-games/src/main/java/net/gazeplay/games/cakes/CakeFactory.java, gazeplay-games/src/main/java/net/gazeplay/games/colors/ColorsGame.java, gazeplay-games/src/main/java/net/gazeplay/games/cups/Cup.java, gazeplay-games/src/main/java/net/gazeplay/games/cups/CupsAndBalls.java, gazeplay-games/src/main/java/net/gazeplay/games/literacy/Bloc.java, gazeplay-games/src/main/java/net/gazeplay/games/literacy/Letters.java, gazeplay-games/src/main/java/net/gazeplay/games/magiccards/Card.java, gazeplay-games/src/main/java/net/gazeplay/games/magiccards/MagicCards.java, gazeplay-games/src/main/java/net/gazeplay/games/math101/Card.java, gazeplay-games/src/main/java/net/gazeplay/games/math101/Math101.java, gazeplay-games/src/main/java/net/gazeplay/games/memory/Memory.java, gazeplay-games/src/main/java/net/gazeplay/games/memory/MemoryCard.java, gazeplay-games/src/main/java/net/gazeplay/games/slidingpuzzle/SlidingPuzzle.java, gazeplay-games/src/main/java/net/gazeplay/games/slidingpuzzle/SlidingPuzzleCard.java, gazeplay-games/src/main/java/net/gazeplay/games/whereisit/PictureCard.java, gazeplay-games/src/main/java/net/gazeplay/games/whereisit/WhereIsIt.java
=> Mouse event triggered at game launch #1339

gazeplay-core/src/main/resources/data/multilinguism/multilinguism.csv, gazeplay-games/src/main/java/net/gazeplay/games/bottle/BottleGameLauncher.java, gazeplay-games/src/main/java/net/gazeplay/games/bottle/BottleGameVariantGenerator.java, gazeplay-games/src/main/java/net/gazeplay/games/bubbles/Bubble.java, gazeplay-games/src/main/java/net/gazeplay/games/bubbles/BubblesGameVariant.java
Allow the player to increase the size of the bubble when he watch it, and decrease if not.
Increase the basic size of th bubbles.
=> Bulle taille explosion

gazeplay-core/src/main/java/net/gazeplay/ui/scenes/gamemenu/GameMenuController.java
to avoid playing 2 musics at the same time.
=> Stopping music for launcher when a game is launch 

gazeplay-commons/src/main/resources/logback.xml, gazeplay-games/src/main/java/net/gazeplay/games/race/Race.java
The game is lost when you finish last issue #1314
=> we can lose in the game FrogRace now

gazeplay-commons/src/main/java/net/gazeplay/commons/utils/stats/Stats.java, gazeplay-core/src/main/java/net/gazeplay/ui/scenes/ingame/GameContextFactoryBean.java, gazeplay-games/src/main/java/net/gazeplay/games/creampie/Target.java
Pull Request for the issue #1241 !
It's only temporally stop the mouse recording as long as the menu is open.
=> Stop recording bbb pressed

gazeplay-core/src/main/java/net/gazeplay/ui/scenes/configuration/ConfigurationContext.java
Permet de rendre les sous-menus plus intuitif.
=> Sub parameters

gazeplay-games/src/main/java/net/gazeplay/games/draw/DrawBuilder.java, gazeplay-games/src/main/java/net/gazeplay/games/follow/Follow.java
Now, the scribble game + follow the path work fine with tobbi selected in the parameters and played with the mouse
=> Draw a line in the scribble game #1407 + same problem in follow the path

gazeplay-core/src/main/java/net/gazeplay/ui/scenes/userselect/UserProfileContext.java
The application don't crash but we still don't catch if the file is an image or not (issue #1500 )
=> Crash 2 #1500

gazeplay-core/src/main/java/net/gazeplay/ui/scenes/userselect/UserProfileContext.java
=> let new users being editable

gazeplay-commons/src/main/java/net/gazeplay/commons/utils/games/Utils.java, gazeplay-core/src/main/java/net/gazeplay/ui/scenes/gamemenu/HomeMenuScreen.java, gazeplay-core/src/main/java/net/gazeplay/ui/scenes/userselect/UserProfileContext.java
=> Crash #1497

gazeplay-games/src/main/java/net/gazeplay/games/opinions/OpinionsGame.java
The last background image is the last the user voted for.
=> Opinion game fixed background #1475

gazeplay-games-commons/src/main/java/net/gazeplay/components/GazeFollowerIndicator.java, gazeplay-games/src/main/java/net/gazeplay/games/colors/ColorBox.java, gazeplay-games/src/main/java/net/gazeplay/games/colors/ColorToolBox.java, gazeplay-games/src/main/java/net/gazeplay/games/colors/ColorsGame.java, gazeplay-games/src/main/java/net/gazeplay/games/colors/CustomColorBox.java, gazeplay-games/src/main/java/net/gazeplay/games/colors/CustomColorPicker.java
=> Fixing custom dialog for colors #1472 and #1243

gazeplay-games/src/main/java/net/gazeplay/games/horses/Horses.java
The bug with the dice picture was fixed.
=> Dice picture fixed #1481

gazeplay-games/src/main/java/net/gazeplay/games/space/SpaceGame.java
=> adapted moving background in SpaceGame fixe #1470

CONTRIBUER.MD, CONTRIBUTING.MD
=> link a pr to a ticket

gazeplay-games/src/main/java/net/gazeplay/games/pianosight/Piano.java, gazeplay-games/src/main/java/net/gazeplay/games/pianosight/Tile.java
- The position of the progress indicator on the bottom right key was fixed.
- There was a bug when selecting wrong buttons before selecting the very first key to play. Now works fine.
- The progress indicator on the center circle key was handled correctly.
=> Piano game issue #1487

gazeplay-core/src/main/java/net/gazeplay/ui/scenes/ingame/GameContext.java, gazeplay-core/src/main/java/net/gazeplay/ui/scenes/ingame/GameContextFactoryBean.java
=> Fixing control panel width

gradle/templates/licence.txt
Ajout des nouveaux stagiaires, des soutiens financier, de Marion et Amélie...
=> Mise à jour de la licence pour 1.9.0 et 2021

gazeplay-commons/src/main/resources/logback.xml, gazeplay-games/src/main/java/net/gazeplay/games/dottodot/DotEntity.java, gazeplay-games/src/main/java/net/gazeplay/games/dottodot/DotToDot.java
=> [Dot to Dot] fixing display issue in dark mode

gazeplay-commons/src/main/java/net/gazeplay/commons/configuration/Configuration.java, gazeplay-commons/src/main/java/net/gazeplay/commons/utils/stats/Stats.java, gazeplay-core/src/main/java/net/gazeplay/ui/scenes/configuration/ConfigurationContext.java, gazeplay-core/src/main/resources/data/multilinguism/multilinguism.csv, gazeplay-core/src/test/java/net/gazeplay/ui/scenes/configuration/ConfigurationContextTest.java
allow the user to have a screenshot every 500ms, this option is in settings
=> Screenshots

gazeplay-core/src/main/java/net/gazeplay/ui/scenes/userselect/UserProfileContext.java, gazeplay-core/src/test/java/net/gazeplay/ui/scenes/stats/StatsContextTest.java, gazeplay-games/src/main/java/net/gazeplay/games/labyrinth/Labyrinth.java, gazeplay-games/src/main/java/net/gazeplay/games/labyrinth/Mouse.java
Fix bug #1599
It is now possible to add a custom profile picture.
=> Add custom profile picture

gazeplay-games-commons/src/main/java/net/gazeplay/components/RandomPositionGenerator.java, gazeplay-games/src/main/java/net/gazeplay/games/creampie/Target.java
Fix target position in CreamPie game #1531
=> [CreamPie] target outside the window #1531

gazeplay-commons/src/main/java/net/gazeplay/commons/configuration/Configuration.java, gazeplay-commons/src/main/java/net/gazeplay/commons/utils/stats/Stats.java, gazeplay-core/src/main/java/net/gazeplay/ui/scenes/configuration/ConfigurationContext.java, gazeplay-core/src/main/resources/data/multilinguism/multilinguism.csv, gazeplay-core/src/test/java/net/gazeplay/ui/scenes/configuration/ConfigurationContextTest.java
=> Add function + tests

gazeplay-commons/src/main/java/net/gazeplay/commons/utils/stats/Stats.java, gazeplay-core/src/main/java/net/gazeplay/ReplayingGameFromJson.java, gazeplay-core/src/main/java/net/gazeplay/ui/scenes/gamemenu/GameMenuController.java, gazeplay-core/src/main/java/net/gazeplay/ui/scenes/gamemenu/GameVariantDialog.java, gazeplay-core/src/main/java/net/gazeplay/ui/scenes/ingame/GameContext.java, gazeplay-games/src/main/java/net/gazeplay/games/memory/MemoryGameVariantGenerator.java, gazeplay-games/src/main/java/net/gazeplay/games/whereisit/gamevariantgenerator/WhereIsItDifficultyGameVariantGenerator.java, gazeplay-games/src/main/java/net/gazeplay/games/whereisit/gamevariantgenerator/WhereIsItDynamicGameVariantGenerator.java
fix #1587 
fix #1588 
fix #1589 
Disable some settings during replay.
Answer time not readded in stats.
Cursor not only appears on first rounds enymore.
Where is it? and Memory normal variants are now replayable.
=> Fix bugs about replaying game

gazeplay-games/src/main/java/net/gazeplay/games/dottodot/DotEntity.java
=> Fix dot to dot game

gazeplay-games-commons/src/main/java/net/gazeplay/components/RandomPositionGenerator.java, gazeplay-games/src/main/java/net/gazeplay/games/divisor/Divisor.java
=> fix divisor target stuck on sides #1473

gazeplay-commons/src/main/java/net/gazeplay/commons/utils/stats/Stats.java, gazeplay-commons/src/test/resources/data/multilinguism/multilinguism.csv, gazeplay-core/src/main/java/net/gazeplay/ui/scenes/stats/StatsContext.java, gazeplay-core/src/main/resources/data/multilinguism/multilinguism.csv, gazeplay-core/src/main/resources/net/gazeplay/JSON-schema-replayData.json, gazeplay-games/src/main/java/net/gazeplay/games/math101/Card.java, gazeplay-games/src/main/java/net/gazeplay/games/math101/Math101.java
=> Display number of mistakes in Math Games

gazeplay-commons/src/main/java/net/gazeplay/commons/configuration/Configuration.java, gazeplay-core/src/main/java/net/gazeplay/ui/BackgroundColorControl.java, gazeplay-core/src/main/java/net/gazeplay/ui/ProgressBarControl.java, gazeplay-core/src/main/java/net/gazeplay/ui/scenes/configuration/ConfigurationContext.java, gazeplay-core/src/main/java/net/gazeplay/ui/scenes/ingame/GameContext.java, gazeplay-core/src/main/java/net/gazeplay/ui/scenes/ingame/GameContextFactoryBean.java, gazeplay-core/src/main/resources/data/multilinguism/multilinguism.csv
=> add an option to change background color in games
