BUILD.MD, LICENSE, gazeplay-melordi/pom.xml, gazeplay-picto-pick/pom.xml, gazeplay-tobii-setup/pom.xml, gazeplay/pom.xml, gazeplay/src/license/licenses.xml, gazeplay/src/main/resources/data/common/licence.txt, pom.xml
version tag and build date are now included automatically in license.txt file
third parties libraries name and licenses can now be included automatically in generated JAR file. 
According to third parties license terms, the full license text should be provided with the distributed binaries.
=> About License

.travis.yml, gazeplay-commons/pom.xml
Travis CI should work now
I tried to make it work with openjdk8 in TravisCI. But I still fail to get openjfx installed on trusty.
And xenial seem to be just an alias for trusty, so it fails also. That's too bad, because it seems it would work on xenial, as per my test in a xenial docker container.
=> only use oraclejdk with TravisCI for the moment

pom.xml
in order to get predicable result when building on Windows
=> enforce line ending to LF in .java source files

gazeplay-commons/src/main/java/net/gazeplay/commons/gaze/GazeUtils.java
highlights potential memory leak in 'Where Is It' games
=> print the number of listeners in GazeUtils

gazeplay-commons/src/main/java/net/gazeplay/commons/gaze/devicemanager/AbstractGazeDeviceManager.java
events should be fired on the JavaFx Thread
because it will eventually trigger animations + using thread safe List for storing registered events listeners, as they may be added or removed will the lists is beeing iterated over
=> events should be fired on the JavaFx Thread

gazeplay-dist/src/main/bin/gazeplay.bat
this dll directory is created at runtime by coylz/TobiiStreamEngineForJava with a name that is known in advance.
```gazeplay.bat``` that is provided in the dist zip file should add the dll directory to the PATH, in order for it to appear in the ```java.library.path``` system property.
=> added dll directory to PATH

gazeplay/src/main/java/net/gazeplay/commons/utils/multilinguism/Multilinguism.java
in case a translation is missing, return the key, with a warning prefix, in order to have be able to work in a degraded mode
=> Permissive Translation System with a degraded mode in case of missing translation

gazeplay-data/src/main/resources/data/stylesheets/base.css, gazeplay/src/main/java/net/gazeplay/HomeMenuScreen.java, gazeplay/src/main/java/net/gazeplay/commons/utils/CssUtil.java
added a new Game Chooser that works with buttons instead of a ChoiceBox. 
Games with multiple variants are grouped, then when selected, a dialog is shown in order to choose the variant. When no variant is available, the game is launched immediately
=> Alternative Game Chooser

gazeplay-commons/src/main/java/net/gazeplay/commons/utils/games/Utils.java, gazeplay-data/src/main/resources/data/stylesheets/base-max-width-0800.css, gazeplay-data/src/main/resources/data/stylesheets/base-max-width-1024.css, gazeplay-data/src/main/resources/data/stylesheets/base-max-width-1280.css, gazeplay-data/src/main/resources/data/stylesheets/base-max-width-1366.css, gazeplay-data/src/main/resources/data/stylesheets/base-max-width-1440.css, gazeplay-data/src/main/resources/data/stylesheets/base-max-width-1600.css, gazeplay-data/src/main/resources/data/stylesheets/base-max-width-1920.css, gazeplay-data/src/main/resources/data/stylesheets/base-max-width-2560.css, gazeplay-data/src/main/resources/data/stylesheets/base.css, gazeplay/src/main/java/net/gazeplay/GraphicalContext.java, gazeplay/src/main/java/net/gazeplay/HomeMenuScreen.java, gazeplay/src/main/java/net/gazeplay/commons/utils/CssUtil.java
Multiple improvement on the graphical design of the game home menu
- game thumbnail is now on the left of the button, and the game name is bigger on the right
- buttons do not resize when the window resizes. This is better as the button will always look the same whatever the window size.
- use a ScrollPane in order to contain the FlowPane. This permits the buttons to flow according to the available size. When the window is reduced, a scoller is displayed, so that the user can scroll down and up to see all the buttons
- introduced a CSS stylesheet per screen resolution. The screen width is detected, and according to this, an additional stylesheet is loaded, that can override any base style. This permits to have the best size for each resolution. This avoids having to use code to implement …
=> Graphical improvement on game menu

gazeplay/src/main/java/net/gazeplay/GameContext.java, gazeplay/src/main/java/net/gazeplay/games/magiccards/Card.java
Fixed by adding an event when the dezoom animation is finished. The event set the X and Y of the card to the initial ones so we are sure that the card will be at its initial position.
This should do it for this issue. I've tested it a little but it may be not enough. Don't hesitate to reopen the issue if it is still there
=> Fix issue#227

gazeplay-commons/src/main/java/net/gazeplay/commons/threads/CustomThreadFactory.java, gazeplay-commons/src/main/java/net/gazeplay/commons/threads/GroupingThreadFactory.java, gazeplay-commons/src/main/java/net/gazeplay/commons/threads/LoggingUncaughtExceptionHandler.java, gazeplay-commons/src/main/java/net/gazeplay/commons/utils/games/BackgroundMusicManager.java, gazeplay/src/main/java/net/gazeplay/AsyncUiTaskExecutor.java, gazeplay/src/main/java/net/gazeplay/GameContext.java, gazeplay/src/main/java/net/gazeplay/GazePlayLauncher.java, gazeplay/src/main/java/net/gazeplay/commons/utils/Bravo.java, gazeplay/src/main/java/net/gazeplay/games/drawonvideo/VideoPlayerWithLiveFeedbackApp.java
naming Threads so that logs (where each line contains the thread name) are more meaningful, also use Thread pool depending on usage.
=> Naming Threads

.gitignore, gazeplay-commons/src/main/java/net/gazeplay/commons/utils/games/ImageDirectoryLocator.java, gazeplay-commons/src/main/java/net/gazeplay/commons/utils/games/ImageUtils.java
In ```ImageDirectoryLocator```
Tests if an additional relative path (to working directory) exists as a directory.
If a directory exists with this path, then use it as an image directory.
This is a workaround for NetBeans that seems to set module classpath to JARs in maven local repository, where IntelliJ sets classpath to resources from other project's modules.
Should fix issue #359
=> NetBeans support

gazeplay-commons/src/main/java/net/gazeplay/commons/utils/games/BackgroundMusicManager.java
This is to fix what i have done to solve issue #417. Now game music (provided by GameSpec url) won't play if a custom music folder has been set.
=> Fixed a bad if condition

gazeplay-commons/src/main/java/net/gazeplay/commons/utils/stats/Stats.java, gazeplay/src/main/java/net/gazeplay/StatsContext.java, gazeplay/src/main/java/net/gazeplay/games/bubbles/Bubble.java
This push is a follow up of problem #611. I have added the shoot ratio tracking for the bubble game. I would like to note that there is a bug when the user enters a bubble, the number of goals is incremented twice. For now, I have worked around this issue to implement the ratio for the bubble game.
=> Added shots ratio for bubble games [TRAVIS VALIDATED]

gazeplay-commons/src/main/java/net/gazeplay/commons/utils/HeatMap.java
Added a transparent background, so it's easier to see the paths taken by the user:
=> Heat map, eye paths

gazeplay/src/main/java/net/gazeplay/AreaOfInterest.java
I have noticed a stackOverFlowError on window machines and other machines with a small memory capacity that is caused by the recursive method used to calculate the AOI.
I have changed it to a loop instead.
Sorry for any inconveniences.
=> Aoi performance improvement

build.gradle, gazeplay-commons/build.gradle, gazeplay-dist/src/main/bin/gazeplay-linux.sh, gazeplay-dist/src/main/bin/gazeplay-macos.sh, gazeplay-dist/src/main/bin/gazeplay-win10.bat, gazeplay-dist/src/main/bin/gazeplay.bat, gazeplay-games-commons/build.gradle, gazeplay-games/build.gradle, gazeplay/build.gradle
Fixed all JARs generated MANIFEST.MF. 
Fixed Linux launcher .sh script.
Fixed jar name in Windows and Mac launcher scripts.
Distrib now works on GNU/Linux, just unzip then execute ./bin/gazeplay-linux.sh
Not tested on Windows or Mac yet.
=> Fix issues with generated distrib

.github/workflows/gradle.yml
Use GitHub Actions workflow to package the project and push it to an Amazon S3 bucket.
So that snapshots can be downloaded and used ASAP by testers and users.
=> Deploy to S3

build.gradle, gradle/wrapper/gradle-wrapper.properties, settings.gradle
There are a number of QoL upgrades in Gradle 6, as explained in the [release notes](https://docs.gradle.org/current/release-notes.html).
=> Upgrade Gradle Wrapper to v6.0.1

gazeplay-commons/src/main/java/net/gazeplay/commons/configuration/Configuration.java, gazeplay-commons/src/main/java/net/gazeplay/commons/utils/games/BackgroundMusicManager.java, gazeplay-commons/src/test/java/net/gazeplay/commons/utils/games/BackgroundMusicManagerTest.java, gazeplay/src/main/java/net/gazeplay/commons/utils/stats/StatsDisplay.java, gazeplay/src/main/java/net/gazeplay/ui/scenes/configuration/ConfigurationContext.java, gazeplay/src/main/java/net/gazeplay/ui/scenes/gamemenu/GameMenuController.java, gazeplay/src/test/java/net/gazeplay/commons/utils/stats/StatsDisplayTest.java, gazeplay/src/test/java/net/gazeplay/ui/scenes/configuration/ConfigurationContextMusicTest.java, gazeplay/src/test/java/net/gazeplay/ui/scenes/gamemenu/GameMenuControllerTest.java, gazeplay/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
This intends to fix #1011 
The initial idea is to check if the default music is playing, and use that as a basis for whether the user wants to hear their own music, or the music chosen by us for the game. I believe we should always favour the user's music.
Next steps are to make sure the default music is restarted when the game exits.
=> Changing the Backgound Music for games

docs/_includes/masthead.html, docs/_pages/installation.md, docs/_pages/updates/latest_version1.7_eng.md, docs/_pages/updates/latest_version1.7_fra.md, docs/_pages/updates/latest_version_eng.md, docs/fr/_pages/installation.md, docs/index-fr.md, docs/index.md
Now that v1.7.0 is released, the links the app will point to are a bit off. This will fix them, and also make changes around the site to point to the new version.
=> Updated Website with links to new version

.github/workflows/cd.yml, build.gradle, gradle/innosetup/setup.iss.skel, gradle/installer.gradle
include build of the Windows installer distributable file in the CD pipeline. 
InnoSetup is executed in a linux docker container running wine.
also:
- windows distributable file name now contains version label, as other distributable files.
- disabled spring boot jar, zip, tar.
- all distributable files can be uploaded to S3
=> InnoSetup Windows installer build on Linux

gazeplay-commons/src/main/resources/logback.xml, gazeplay-dist/src/main/bin/gazeplay-linux.sh, gazeplay-dist/src/main/bin/gazeplay-macos.sh, gazeplay-dist/src/main/bin/gazeplay-windows.bat
use WARN logging threshold for console appender when running for launcher scripts, to avoid logging many message to console for end users. By default, uses INFO level to have more log message for instance when running from the IDE
=> Console appender loggging Threshold

build.gradle, pmd-ruleset.xml
pmd plugin performs static analysis on code base.
it helps enforcing coding conventions.
for the moment, the plugin is enabled by default but does not fail the build when a violation is found,
because there are a lot of existing violations in the current code base.
so the idea is to iteratively fix all existing violations
and when it's done, make the plugin fail the build so that no new violation comes in. 
You can run pmd analysis by running
```
./gradlew pmdMain
```
You can see violation in browser by running
```
find . -name "*.html" | grep pmd | xargs firefox
```
=> add pmd plugin

gazeplay/src/main/java/net/gazeplay/commons/utils/FileUtils.java, gazeplay/src/main/java/net/gazeplay/ui/scenes/userselect/UserProfilContext.java, gazeplay/src/test/java/net/gazeplay/commons/utils/FileUtilsTest.java
`FilesUtilities` - [ClassNamingConventions](https://pmd.github.io/pmd-6.17.0/pmd_rules_java_codestyle.html#classnamingconventions)
Simply changing the class name is enough to get this to match naming conventions.
Added full test coverage
=> PMD Problems - FilesUtilities

gazeplay-commons/src/main/java/net/gazeplay/commons/themes/BuiltInUiTheme.java
, in replacement of the 'Green' theme. The 'Silver and Gold' theme is considered more classic than the 'Green' one, thus should fit more people
=> Promote 'Silver and Gold' as default theme for UI

.github/workflows/ci.yml, .travis.yml, build.gradle
introduced a check task that checks PMD reports, and fails if the number of violation for any priority level is over a predefinied limit. This allows to acknowledge existing number of violations while preventing introduction of new violations
=> check PMD to prevent introduction of more violations

gradle/innosetup/setup.iss.skel
Solves #1074 
Gets the Uninstaller and offers to run it if it detects the App already installed.
=> Solving #1074 - Uninstall GazePlay if already installed

gazeplay/src/main/java/net/gazeplay/commons/utils/stats/StatDisplayUtils.java, gazeplay/src/test/java/net/gazeplay/commons/utils/stats/StatDisplayUtilsTest.java
Fixes issue #1084
Turns out using `Date` for time differences so low makes it think its 01/01/1970 01:00:00, adding an extra 1 day and 1 hour to the difference.
Instead doing some maths with the `TimeUnit` and formatting it in the desired manner makes it work correctly.
=> Fix for time problem in stats

gazeplay/src/main/java/net/gazeplay/ui/scenes/configuration/ConfigurationContext.java, gazeplay/src/test/java/net/gazeplay/ui/scenes/configuration/ConfigurationContextTest.java
Noticed this hasn't been working for a while. 
The Folder buttons in `ConfigurationContext` don't update with the configuration change due to the `configuration` object being cleared up by the GC. I've moved the update into the `setOnAction` listeners on each button.
=> Fix Folder Button binding

gradle/jre/linux.gradle, gradle/jre/macos.gradle, gradle/jre/windows.gradle
Fixes #1130
The problem was that in the packaged download we weren't extracting the actual JRE files from the root folder. This fixes that with an extra task that performs this extraction and another that does a bit of tidying up.
=> Extracting the inner folder from downloaded JREs

gazeplay-games/src/main/java/net/gazeplay/games/slidingpuzzle/SlidingPuzzleCard.java
reverse useless check added for timelineProgressBar on gazeEnter making game unusable
=> fixing issue with progressBar bad if check in sliding puzzle game

gazeplay-commons/src/main/java/net/gazeplay/commons/utils/multilinguism/I18N.java, gazeplay-commons/src/main/java/net/gazeplay/commons/utils/multilinguism/LanguageDetails.java, gazeplay-commons/src/main/java/net/gazeplay/commons/utils/multilinguism/Languages.java, gazeplay-commons/src/test/java/net/gazeplay/commons/utils/multilinguism/LanguagesTest.java
`I18N` 
[AvoidFileStream](https://pmd.github.io/pmd-6.17.0/pmd_rules_java_performance.html#avoidfilestream) - line 35
`Languages`
[AvoidReassigningParameters](https://pmd.github.io/pmd-6.17.0/pmd_rules_java_bestpractices.html#avoidreassigningparameters) - line 111
Changed to `Files.newFileStream` and added mid-method parameter.
* 100% test coverage of Languages
=> PMD Problems - I18N and Languages

gradle/innosetup/setup.iss.skel, gradle/installer.gradle
Fixes #1144 
The problem (since 7th Feb) was caused by the dirMode not being set on Unix, and that meant that the Docker container couldn't mount that directory, or InnoSetup couldn't access it. This has been fixed now, and testing in the GitHub Actions environment.
=> Fixing CD-made installer

.github/workflows/release.yml, build.gradle, gradle/innosetup/setup.iss.skel, gradle/installer.gradle, gradle/package.gradle, settings.gradle
This will help us on our way to simplifying releases.
This new action is set up to run whenever `develop` is merged into `master`. It will build the project with the release version number (which must be set before merging), create the GitHub release and upload all the necessary artifacts. 
I also made the naming conventions for everything uniform, including changing the project name from `gazeplay-project` to simply `gazeplay`.
=> GitHub Actions for Releases

.github/workflows/ci.yml
With this PR we can now download the Test Reports from any new CI Build
=> Adding Artifact Upload to CI workflow

gazeplay-games-commons/src/main/java/net/gazeplay/GameSummary.java, gazeplay-games-commons/src/main/java/net/gazeplay/GameSummaryComparator.java, gazeplay-games-commons/src/test/java/net/gazeplay/GameSummaryComparatorTest.java, gazeplay-games/src/main/java/net/gazeplay/games/creampie/CreampieGameSpecSource.java, gazeplay-games/src/main/java/net/gazeplay/games/ninja/NinjaGameSpecSource.java
This solves #1145 
I added a new property to the `GameSummary` object to allow custom absolute priorities, that will move games up to the top of the list.
Also adding tests for the comparator
=> Changing Game Order

gazeplay-games/src/main/java/net/gazeplay/games/memory/Memory.java
All cards are fully displayed even when exiting the full-screen mode.
=> Adapted display of cards in Memory #1488

gazeplay-core/src/main/java/net/gazeplay/ui/scenes/ingame/GameContextFactoryBean.java, gazeplay-games/src/main/java/net/gazeplay/games/dice/Dice.java
- It was impossible to see the value on the dice in the light mode, now fixed.
- FIxed #1474, I suggested changing the background color from white to light grey in the light mode .-. Seems like it works in other games too
=> Dice game light mode fixed #1474

gazeplay-commons/src/main/java/net/gazeplay/commons/utils/stats/Stats.java, gazeplay-games/src/main/java/net/gazeplay/games/bubbles/Bubble.java, gazeplay-games/src/main/java/net/gazeplay/games/bubbles/Target.java, gazeplay-games/src/main/java/net/gazeplay/games/flowerOfNumbers/FlowerOfNumbersGame.java, gazeplay-games/src/main/java/net/gazeplay/games/flowerOfNumbers/FlowerOfNumbersGameLauncher.java
fix #1575
Bubbles now appear on screenshots of Bubbles games.
Numerical items now appear on screenshots of the Flower of Numbers game.
Screenshot are no longer unnecessarily taken in replay mode.
=> Screenshot fixes
